/* সূত্র — নমুনা ডেটা। মালিকানা, অবস্থান ও শিরোনাম শুধু ডেমোর জন্য;
   বাস্তব পোর্টালের নাম ব্যবহার হলেও তথ্যগুলো সম্পাদকীয় দাবি নয়। */

const STANCES = {
  govt:    { label: 'সরকার-ঘেঁষা', short: 'ঘেঁষা',     cls: 'govt' },
  neutral: { label: 'নিরপেক্ষ',    short: 'নিরপেক্ষ', cls: 'neutral' },
  critic:  { label: 'সমালোচক',    short: 'সমালোচক',  cls: 'critic' },
};

const OWNER_TYPES = {
  corporate:   { label: 'কর্পোরেট',   mark: '◆' },
  party:       { label: 'দল-ঘনিষ্ঠ', mark: '●' },
  independent: { label: 'স্বাধীন',    mark: '○' },
};

const SOURCES = {
  'prothom-alo': {
    name: 'প্রথম আলো', mono: 'প্রআ', type: 'corporate',
    typeLabel: 'কর্পোরেট (মিডিয়া-প্রধান)',
    kind: 'দৈনিক · প্রিন্ট + অনলাইন', founded: '১৯৯৮',
    owner: 'মিডিয়াস্টার লিমিটেড', group: 'ট্রান্সকম গ্রুপ',
    businesses: 'ঔষধ · পানীয় · ইলেকট্রনিক্স',
    chain: ['প্রথম আলো', 'মিডিয়াস্টার লিমিটেড', 'ট্রান্সকম গ্রুপ'],
    siblings: ['ডেইলি স্টার (আংশিক)'],
    revenue: 'বিজ্ঞাপন · সাবস্ক্রিপশন',
    pattern: { govt: 21, neutral: 54, critic: 25 },
    conflict: null,
  },
  'kaler-kantho': {
    name: 'কালের কণ্ঠ', mono: 'কক', type: 'corporate',
    typeLabel: 'কর্পোরেট (শিল্পগোষ্ঠী)',
    kind: 'দৈনিক · প্রিন্ট + অনলাইন', founded: '২০১০',
    owner: 'ইস্ট ওয়েস্ট মিডিয়া গ্রুপ', group: 'বসুন্ধরা গ্রুপ',
    businesses: 'আবাসন · সিমেন্ট · কাগজ · জ্বালানি',
    chain: ['কালের কণ্ঠ', 'ইস্ট ওয়েস্ট মিডিয়া', 'বসুন্ধরা গ্রুপ'],
    siblings: ['বাংলাদেশ প্রতিদিন', 'ডেইলি সান', 'নিউজ২৪ টিভি', 'রেডিও ক্যাপিটাল'],
    revenue: 'বিজ্ঞাপন · গ্রুপ ভর্তুকি',
    pattern: { govt: 55, neutral: 35, critic: 10 },
    conflict: 'আবাসন ও জ্বালানি খাতের খবরে মূল গ্রুপের ব্যবসায়িক স্বার্থ জড়িত থাকতে পারে',
  },
  'bd-protidin': {
    name: 'বাংলাদেশ প্রতিদিন', mono: 'বাপ্র', type: 'corporate',
    typeLabel: 'কর্পোরেট (শিল্পগোষ্ঠী)',
    kind: 'দৈনিক · প্রিন্ট + অনলাইন', founded: '২০১০',
    owner: 'ইস্ট ওয়েস্ট মিডিয়া গ্রুপ', group: 'বসুন্ধরা গ্রুপ',
    businesses: 'আবাসন · সিমেন্ট · কাগজ · জ্বালানি',
    chain: ['বাংলাদেশ প্রতিদিন', 'ইস্ট ওয়েস্ট মিডিয়া', 'বসুন্ধরা গ্রুপ'],
    siblings: ['কালের কণ্ঠ', 'ডেইলি সান', 'নিউজ২৪ টিভি'],
    revenue: 'বিজ্ঞাপন · গ্রুপ ভর্তুকি',
    pattern: { govt: 50, neutral: 38, critic: 12 },
    conflict: 'আবাসন ও জ্বালানি খাতের খবরে মূল গ্রুপের ব্যবসায়িক স্বার্থ জড়িত থাকতে পারে',
  },
  'jugantor': {
    name: 'যুগান্তর', mono: 'যু', type: 'corporate',
    typeLabel: 'কর্পোরেট (শিল্পগোষ্ঠী)',
    kind: 'দৈনিক · প্রিন্ট + অনলাইন', founded: '২০০০',
    owner: 'যমুনা গ্রুপ', group: 'যমুনা গ্রুপ',
    businesses: 'ইলেকট্রনিক্স · আবাসন · টেক্সটাইল',
    chain: ['যুগান্তর', 'যমুনা গ্রুপ'],
    siblings: ['যমুনা টিভি'],
    revenue: 'বিজ্ঞাপন · গ্রুপ ভর্তুকি',
    pattern: { govt: 40, neutral: 42, critic: 18 },
    conflict: 'ইলেকট্রনিক্স ও আবাসন খাতের খবরে মূল গ্রুপের ব্যবসায়িক স্বার্থ জড়িত থাকতে পারে',
  },
  'ittefaq': {
    name: 'দৈনিক ইত্তেফাক', mono: 'ইত্তে', type: 'corporate',
    typeLabel: 'কর্পোরেট (মিডিয়া-প্রধান)',
    kind: 'দৈনিক · প্রিন্ট + অনলাইন', founded: '১৯৫৩',
    owner: 'ইত্তেফাক গ্রুপ অব পাবলিকেশন্স', group: 'ইত্তেফাক গ্রুপ',
    businesses: 'প্রকাশনা',
    chain: ['দৈনিক ইত্তেফাক', 'ইত্তেফাক গ্রুপ অব পাবলিকেশন্স'],
    siblings: [],
    revenue: 'বিজ্ঞাপন · সাবস্ক্রিপশন',
    pattern: { govt: 30, neutral: 52, critic: 18 },
    conflict: null,
  },
  'bdnews24': {
    name: 'বিডিনিউজ২৪', mono: 'বিডি', type: 'independent',
    typeLabel: 'স্বাধীন ডিজিটাল',
    kind: 'অনলাইন সংবাদ সংস্থা', founded: '২০০৬',
    owner: 'স্বাধীন ডিজিটাল', group: '—',
    businesses: '—',
    chain: ['বিডিনিউজ২৪', 'স্বাধীন ডিজিটাল'],
    siblings: [],
    revenue: 'বিজ্ঞাপন · সাবস্ক্রিপশন',
    pattern: { govt: 18, neutral: 64, critic: 18 },
    conflict: null,
  },
  'manabzamin': {
    name: 'মানবজমিন', mono: 'মজ', type: 'independent',
    typeLabel: 'স্বাধীন',
    kind: 'দৈনিক ট্যাবলয়েড · প্রিন্ট + অনলাইন', founded: '১৯৯৮',
    owner: 'পরিবার-মালিকানাধীন', group: '—',
    businesses: '—',
    chain: ['মানবজমিন', 'পরিবার-মালিকানাধীন'],
    siblings: [],
    revenue: 'বিজ্ঞাপন · সাবস্ক্রিপশন',
    pattern: { govt: 8, neutral: 32, critic: 60 },
    conflict: null,
  },
  'naya-diganta': {
    name: 'নয়া দিগন্ত', mono: 'নদি', type: 'party',
    typeLabel: 'দল-ঘনিষ্ঠ',
    kind: 'দৈনিক · প্রিন্ট + অনলাইন', founded: '২০০৪',
    owner: 'দিগন্ত মিডিয়া করপোরেশন', group: 'দিগন্ত মিডিয়া',
    businesses: 'মিডিয়া',
    chain: ['নয়া দিগন্ত', 'দিগন্ত মিডিয়া করপোরেশন'],
    siblings: ['দিগন্ত টিভি (বন্ধ)'],
    revenue: 'বিজ্ঞাপন · পৃষ্ঠপোষকতা',
    pattern: { govt: 6, neutral: 28, critic: 66 },
    conflict: 'রাজনৈতিক ঘনিষ্ঠতার কারণে দলীয় ইস্যুতে অবস্থান একপেশে হতে পারে',
  },
  'samakal': {
    name: 'সমকাল', mono: 'সম', type: 'corporate',
    typeLabel: 'কর্পোরেট (শিল্পগোষ্ঠী)',
    kind: 'দৈনিক · প্রিন্ট + অনলাইন', founded: '২০০৫',
    owner: 'টাইমস মিডিয়া লিমিটেড', group: 'হা-মীম গ্রুপ',
    businesses: 'তৈরি পোশাক · টেক্সটাইল',
    chain: ['সমকাল', 'টাইমস মিডিয়া লিমিটেড', 'হা-মীম গ্রুপ'],
    siblings: ['চ্যানেল ২৪'],
    revenue: 'বিজ্ঞাপন · গ্রুপ ভর্তুকি',
    pattern: { govt: 22, neutral: 50, critic: 28 },
    conflict: 'তৈরি পোশাক খাতের (শ্রমিক-মজুরি) খবরে মূল গ্রুপের ব্যবসায়িক স্বার্থ জড়িত থাকতে পারে',
  },
  'janakantha': {
    name: 'দৈনিক জনকণ্ঠ', mono: 'জক', type: 'corporate',
    typeLabel: 'কর্পোরেট (শিল্পগোষ্ঠী)',
    kind: 'দৈনিক · প্রিন্ট + অনলাইন', founded: '১৯৯৩',
    owner: 'গ্লোব জনকণ্ঠ শিল্প পরিবার', group: 'গ্লোব গ্রুপ',
    businesses: 'ঔষধ · খাদ্য · মুদ্রণ',
    chain: ['দৈনিক জনকণ্ঠ', 'গ্লোব জনকণ্ঠ শিল্প পরিবার'],
    siblings: [],
    revenue: 'বিজ্ঞাপন',
    pattern: { govt: 48, neutral: 40, critic: 12 },
    conflict: null,
  },
};

const TOPICS = ['রাজনীতি', 'অর্থনীতি', 'শ্রম', 'পরিবহন', 'আন্তর্জাতিক', 'খেলা', 'ঢাকা'];

/* reports: কালানুক্রমিক (আগে → পরে)। changes = শিরোনাম বদলের সংখ্যা। */
const CLUSTERS = [
  {
    id: 'dollar', topic: 'অর্থনীতি', lead: true,
    title: 'ডলারের বিপরীতে টাকার দর আরও কমল, রিজার্ভ নিয়ে উদ্বেগ',
    summary: 'আন্তঃব্যাংক বাজারে ডলারের বিপরীতে টাকার দর আরও কমেছে, কেন্দ্রীয় ব্যাংকের হিসাবে রিজার্ভও নিম্নমুখী। সরকার-ঘেঁষা সূত্রগুলো একে সাময়িক চাপ বলছে, সমালোচক সূত্রগুলো নীতি-ব্যর্থতা হিসেবে দেখছে; দরপতনের অঙ্ক নিয়ে অবশ্য কোনো দ্বিমত নেই।',
    reportCount: 42, portalCount: 9,
    updated: '৩০ মিনিট আগে', firstPublished: 'সকাল ৮:০৫',
    blindspot: null,
    reports: [
      { src: 'bdnews24',     stance: 'neutral', time: '৮:০৫',  headline: 'আন্তঃব্যাংকে ডলারের দর আরও বাড়ল, চাপে রিজার্ভ' },
      { src: 'prothom-alo',  stance: 'neutral', time: '৮:৪০',  headline: 'ডলারের বিপরীতে টাকার দর আরও কমল' },
      { src: 'kaler-kantho', stance: 'govt',    time: '৯:১৫',  headline: 'রিজার্ভ স্থিতিশীল রাখতে সরকারের বহুমুখী উদ্যোগ' },
      { src: 'ittefaq',      stance: 'neutral', time: '৯:৫০',  headline: 'টাকার দরপতন অব্যাহত, আমদানিতে বাড়তি ব্যয়ের শঙ্কা' },
      { src: 'bd-protidin',  stance: 'govt',    time: '১০:২০', headline: 'ডলার সংকট সামলাতে সাহসী পদক্ষেপ নিচ্ছে সরকার' },
      { src: 'manabzamin',   stance: 'critic',  time: '১১:০৫', headline: 'রিজার্ভে ধস: সামনে আরও দুঃসময়ের ইঙ্গিত' },
      { src: 'samakal',      stance: 'neutral', time: '১১:৩০', headline: 'ডলারের দাম বাড়ায় ভোগ্যপণ্যের বাজারে অস্থিরতা' },
      { src: 'janakantha',   stance: 'govt',    time: '১১:৫৫', headline: 'বৈশ্বিক সংকটেও অর্থনীতির ভিত মজবুত: অর্থ মন্ত্রণালয়' },
      { src: 'naya-diganta', stance: 'critic',  time: '১২:১০', headline: 'টাকার রেকর্ড দরপতনে দিশেহারা সাধারণ মানুষ' },
    ],
  },
  {
    id: 'wage-protest', topic: 'শ্রম',
    title: 'পোশাক শ্রমিকদের মজুরি বিক্ষোভে লাঠিচার্জের অভিযোগ',
    summary: 'নূন্যতম মজুরি বাড়ানোর দাবিতে গাজীপুরে পোশাক শ্রমিকদের বিক্ষোভ তৃতীয় দিনে গড়িয়েছে; শ্রমিকদের অভিযোগ, পুলিশ লাঠিচার্জ করেছে। পুলিশ বলছে, তারা ‘ন্যূনতম বলপ্রয়োগ’ করেছে। সরকার-ঘেঁষা পোর্টালগুলোর অধিকাংশ খবরটি ছাপেনি।',
    reportCount: 12, portalCount: 7,
    updated: '১ ঘণ্টা আগে', firstPublished: 'সকাল ৯:৩০',
    blindspot: 'govt', blindspotNote: 'ঘেঁষা পোর্টালগুলোর মধ্যে ছেপেছে মাত্র ১টি',
    reports: [
      { src: 'manabzamin',   stance: 'critic',  time: '৯:৩০',  headline: 'মজুরির দাবিতে রাজপথে শ্রমিক, পুলিশের লাঠিচার্জ' },
      { src: 'bdnews24',     stance: 'neutral', time: '১০:০৫', headline: 'গাজীপুরে মজুরি বিক্ষোভ তৃতীয় দিনে, সংঘর্ষের অভিযোগ' },
      { src: 'naya-diganta', stance: 'critic',  time: '১০:৪০', headline: 'শ্রমিকের রক্তে রাজপথ: মজুরি চাইতেই লাঠিপেটা' },
      { src: 'prothom-alo',  stance: 'neutral', time: '১১:১০', headline: 'মজুরি বিক্ষোভে উত্তপ্ত গাজীপুর, আহত অন্তত ১২' },
      { src: 'samakal',      stance: 'critic',  time: '১১:৪৫', headline: 'ন্যায্য মজুরির দাবি কেন বারবার উপেক্ষিত' },
      { src: 'ittefaq',      stance: 'neutral', time: '১২:০৫', headline: 'মজুরি আন্দোলনে স্থবির শিল্পাঞ্চল, আলোচনার আহ্বান' },
      { src: 'janakantha',   stance: 'govt',    time: '১২:২৫', headline: 'শিল্পাঞ্চলে শৃঙ্খলা ফেরাতে তৎপর আইনশৃঙ্খলা বাহিনী' },
      { src: 'manabzamin',   stance: 'critic',  time: '১২:৪০', headline: 'আহত শ্রমিকদের হাসপাতালে ভর্তি, মামলার প্রস্তুতি' },
    ],
  },
  {
    id: 'metro-fare', topic: 'পরিবহন',
    title: 'মেট্রোরেলের ভাড়া ২০ শতাংশ বাড়ছে ১ আগস্ট থেকে',
    summary: 'ঢাকা ম্যাস ট্রানজিট কোম্পানি জানিয়েছে, ১ আগস্ট থেকে মেট্রোরেলের ভাড়া গড়ে ২০ শতাংশ বাড়বে। কর্তৃপক্ষের যুক্তি পরিচালন ব্যয় বৃদ্ধি; যাত্রী ও পরিবহন বিশেষজ্ঞদের একাংশ সিদ্ধান্তের সমালোচনা করেছেন। ভাড়া বৃদ্ধির হার ও কার্যকরের তারিখ নিয়ে সূত্রগুলোর মধ্যে দ্বিমত নেই।',
    reportCount: 8, portalCount: 7,
    updated: '৩০ মিনিট আগে', firstPublished: 'সকাল ৯:১৪',
    blindspot: null,
    reports: [
      { src: 'bdnews24',     stance: 'neutral', time: '৯:১৪',  headline: 'মেট্রোরেলের ভাড়া ২০ শতাংশ বাড়ছে ১ আগস্ট থেকে' },
      { src: 'kaler-kantho', stance: 'govt',    time: '১০:০২', headline: 'যাত্রীসেবা উন্নয়নে মেট্রোরেলের নতুন ভাড়া কাঠামো' },
      { src: 'prothom-alo',  stance: 'neutral', time: '১০:৩০', headline: 'মেট্রোরেলের ভাড়া বাড়ছে ২০ শতাংশ, কার্যকর ১ আগস্ট', changes: 2 },
      { src: 'ittefaq',      stance: 'neutral', time: '১০:৪৮', headline: 'ভাড়া বাড়ানোর সিদ্ধান্তে মিশ্র প্রতিক্রিয়া যাত্রীদের' },
      { src: 'manabzamin',   stance: 'critic',  time: '১১:৪৫', headline: 'জনগণের পকেট কাটছে মেট্রোরেল: এক লাফে ভাড়া ২০%' },
      { src: 'janakantha',   stance: 'govt',    time: '১২:০০', headline: 'বিশ্বমানের সেবা ধরে রাখতেই ভাড়া সমন্বয়: ডিএমটিসিএল' },
      { src: 'bdnews24',     stance: 'neutral', time: '১২:০৫', headline: 'মেট্রোরেলের নতুন ভাড়ার পূর্ণাঙ্গ তালিকা প্রকাশ' },
      { src: 'naya-diganta', stance: 'critic',  time: '১২:২০', headline: 'যাত্রীদের ওপর আবার ভাড়ার বোঝা, ক্ষুব্ধ নগরবাসী' },
    ],
  },
  {
    id: 'port-jam', topic: 'অর্থনীতি',
    title: 'চট্টগ্রাম বন্দরে কনটেইনার জট, রপ্তানিতে শঙ্কা',
    summary: 'চট্টগ্রাম বন্দরে কনটেইনার জট তীব্র হয়ে ওঠায় রপ্তানি চালান পিছিয়ে যাওয়ার শঙ্কায় ব্যবসায়ীরা। বন্দর কর্তৃপক্ষ বলছে, জট দ্রুতই কেটে যাবে; শিপিং এজেন্টদের হিসাবে জাহাজের অপেক্ষার সময় দ্বিগুণ হয়েছে।',
    reportCount: 8, portalCount: 5,
    updated: '২ ঘণ্টা আগে', firstPublished: 'সকাল ৮:৫০',
    blindspot: null,
    reports: [
      { src: 'bdnews24',     stance: 'neutral', time: '৮:৫০',  headline: 'চট্টগ্রাম বন্দরে কনটেইনার জট, ভোগান্তিতে আমদানিকারকরা' },
      { src: 'bd-protidin',  stance: 'govt',    time: '৯:৪০',  headline: 'বন্দরের সক্ষমতা বাড়াতে মেগা পরিকল্পনা কর্তৃপক্ষের' },
      { src: 'prothom-alo',  stance: 'neutral', time: '১০:১৫', headline: 'বন্দরে জট: রপ্তানি চালান পিছিয়ে যাওয়ার শঙ্কা' },
      { src: 'samakal',      stance: 'neutral', time: '১১:০০', headline: 'কনটেইনার জটে বাড়ছে পণ্য খালাসের খরচ' },
      { src: 'manabzamin',   stance: 'critic',  time: '১১:৫০', headline: 'অব্যবস্থাপনায় স্থবির বন্দর, দায় নিচ্ছে না কেউ' },
      { src: 'kaler-kantho', stance: 'govt',    time: '১২:১৫', headline: 'জট নিরসনে দিনরাত কাজ চলছে: বন্দর চেয়ারম্যান' },
    ],
  },
  {
    id: 'rohingya', topic: 'আন্তর্জাতিক',
    title: 'রোহিঙ্গা প্রত্যাবাসনে নতুন সমঝোতার আলোচনা',
    summary: 'মিয়ানমারের সঙ্গে রোহিঙ্গা প্রত্যাবাসন নিয়ে নতুন দফা আলোচনার প্রস্তুতি চলছে বলে জানিয়েছে পররাষ্ট্র মন্ত্রণালয়। সরকার-ঘেঁষা সূত্রগুলো একে কূটনৈতিক সাফল্যের পথ বলছে; সমালোচকরা আগের প্রতিশ্রুতি বাস্তবায়ন না হওয়ার কথা মনে করিয়ে দিচ্ছে।',
    reportCount: 9, portalCount: 6,
    updated: '৩ ঘণ্টা আগে', firstPublished: 'সকাল ৯:০০',
    blindspot: null,
    reports: [
      { src: 'janakantha',   stance: 'govt',    time: '৯:০০',  headline: 'প্রত্যাবাসনে বড় অগ্রগতির পথে বাংলাদেশ' },
      { src: 'bdnews24',     stance: 'neutral', time: '৯:৪৫',  headline: 'রোহিঙ্গা প্রত্যাবাসনে নতুন সমঝোতার আলোচনা শুরু' },
      { src: 'kaler-kantho', stance: 'govt',    time: '১০:২০', headline: 'কূটনৈতিক তৎপরতায় খুলছে প্রত্যাবাসনের দুয়ার' },
      { src: 'prothom-alo',  stance: 'neutral', time: '১১:০০', headline: 'প্রত্যাবাসন আলোচনা: আশ্বাস আছে, নিশ্চয়তা নেই' },
      { src: 'ittefaq',      stance: 'neutral', time: '১১:৪০', headline: 'রোহিঙ্গা ইস্যুতে ঢাকার নতুন কূটনৈতিক উদ্যোগ' },
      { src: 'bd-protidin',  stance: 'govt',    time: '১২:১০', headline: 'সরকারের ধারাবাহিক চাপে নমনীয় মিয়ানমার' },
      { src: 'naya-diganta', stance: 'critic',  time: '১২:৩০', headline: 'সাত বছরে একজনও ফেরেনি — আবারও কি শুধুই আলোচনা?' },
    ],
  },
  {
    id: 'shakib-century', topic: 'খেলা',
    title: 'সিরিজ জয়ে সাকিবের সেঞ্চুরি',
    summary: 'তৃতীয় ওয়ানডেতে সাকিবের অপরাজিত সেঞ্চুরিতে সিরিজ জিতেছে বাংলাদেশ। প্রায় সব পোর্টালের কভারেজই উদ্‌যাপনমুখী; খেলার খবরে অবস্থানের ফারাক স্বাভাবিকভাবেই কম।',
    reportCount: 15, portalCount: 10,
    updated: '৪ ঘণ্টা আগে', firstPublished: 'রাত ৯:৪০ (গতকাল)',
    blindspot: null,
    reports: [
      { src: 'bdnews24',     stance: 'neutral', time: '৯:৪০',  headline: 'সাকিবের সেঞ্চুরিতে সিরিজ বাংলাদেশের' },
      { src: 'prothom-alo',  stance: 'neutral', time: '৯:৫৫',  headline: 'অপরাজিত ১০৪ — সাকিবের ব্যাটে সিরিজ জয়' },
      { src: 'kaler-kantho', stance: 'neutral', time: '১০:১০', headline: 'সাকিব-ঝড়ে উড়ে গেল প্রতিপক্ষ' },
      { src: 'janakantha',   stance: 'govt',    time: '১০:৩০', headline: 'ক্রীড়াঙ্গনে সরকারের বিনিয়োগের ফসল এই জয়' },
      { src: 'manabzamin',   stance: 'neutral', time: '১০:৪৫', headline: 'সেঞ্চুরির রাতে সাকিবের ফেরার গল্প' },
      { src: 'ittefaq',      stance: 'neutral', time: '১১:০০', headline: 'সিরিজ জয়ের নায়ক সাকিব' },
    ],
  },
  {
    id: 'dengue', topic: 'ঢাকা',
    title: 'ঢাকায় ডেঙ্গু রোগী বাড়ছে, হাসপাতালে শয্যা-সংকট',
    summary: 'বর্ষার শুরুতেই ঢাকার হাসপাতালগুলোতে ডেঙ্গু রোগীর চাপ বাড়ছে; স্বাস্থ্য অধিদপ্তরের হিসাবে ভর্তি রোগী গত সপ্তাহের দ্বিগুণ। সিটি করপোরেশন বলছে মশক নিধন অভিযান চলছে, বিশেষজ্ঞরা বলছেন অভিযান যথেষ্ট নয়।',
    reportCount: 11, portalCount: 7,
    updated: '১ ঘণ্টা আগে', firstPublished: 'সকাল ৮:২০',
    blindspot: null,
    reports: [
      { src: 'prothom-alo',  stance: 'neutral', time: '৮:২০',  headline: 'ডেঙ্গুতে একদিনে হাসপাতালে ভর্তি ২১০ জন' },
      { src: 'bdnews24',     stance: 'neutral', time: '৯:০০',  headline: 'ঢাকায় ডেঙ্গু রোগী দ্বিগুণ, শয্যা-সংকটের শঙ্কা' },
      { src: 'samakal',      stance: 'neutral', time: '৯:৫০',  headline: 'ডেঙ্গু মৌসুমের আগেই হাসপাতালে চাপ' },
      { src: 'manabzamin',   stance: 'critic',  time: '১০:৩০', headline: 'মশা মারার বাজেট গেল কোথায়?' },
      { src: 'kaler-kantho', stance: 'govt',    time: '১১:১৫', headline: 'ডেঙ্গু মোকাবিলায় সর্বাত্মক প্রস্তুতি দুই সিটির' },
      { src: 'ittefaq',      stance: 'neutral', time: '১১:৫০', headline: 'ডেঙ্গু: শিশু ওয়ার্ডে বাড়তি শয্যার নির্দেশ' },
      { src: 'naya-diganta', stance: 'critic',  time: '১২:১৫', headline: 'বছর ঘুরলেও বদলায়নি চিত্র, ডেঙ্গুর দায় কার?' },
    ],
  },
  {
    id: 'poll-dialogue', topic: 'রাজনীতি',
    title: 'নির্বাচনী রোডম্যাপ নিয়ে সংলাপের আহ্বান',
    summary: 'আগামী নির্বাচনের রোডম্যাপ নিয়ে রাজনৈতিক দলগুলোর মধ্যে সংলাপের আহ্বান জানিয়েছে নাগরিক সমাজের একটি প্ল্যাটফর্ম। এই ইস্যুতে সূত্রগুলোর অবস্থান কার্যত তিন ভাগে বিভক্ত — প্রায় সমান-সমান।',
    reportCount: 18, portalCount: 9,
    updated: '২ ঘণ্টা আগে', firstPublished: 'সকাল ৮:৩০',
    blindspot: null,
    reports: [
      { src: 'bdnews24',     stance: 'neutral', time: '৮:৩০',  headline: 'নির্বাচনী রোডম্যাপ নিয়ে সংলাপের আহ্বান নাগরিক প্ল্যাটফর্মের' },
      { src: 'kaler-kantho', stance: 'govt',    time: '৯:২০',  headline: 'সংবিধান মেনেই যথাসময়ে নির্বাচন: ক্ষমতাসীন দল' },
      { src: 'manabzamin',   stance: 'critic',  time: '১০:০০', headline: 'সংলাপের নামে সময়ক্ষেপণ চায় না বিরোধীরা' },
      { src: 'prothom-alo',  stance: 'neutral', time: '১০:৪৫', headline: 'সংলাপ নিয়ে দুই পক্ষের শর্তে অচলাবস্থা' },
      { src: 'janakantha',   stance: 'govt',    time: '১১:২০', headline: 'ষড়যন্ত্র নয়, উন্নয়নের ধারাবাহিকতাই জনগণের চাওয়া' },
      { src: 'naya-diganta', stance: 'critic',  time: '১২:০০', headline: 'দাবি না মানলে কঠোর কর্মসূচির হুঁশিয়ারি' },
    ],
  },
  {
    id: 'export-record', topic: 'অর্থনীতি',
    title: 'রপ্তানি আয়ে রেকর্ড প্রবৃদ্ধির ঘোষণা',
    summary: 'গত অর্থবছরে রপ্তানি আয়ে রেকর্ড প্রবৃদ্ধি হয়েছে বলে জানিয়েছে রপ্তানি উন্নয়ন ব্যুরো। খবরটি সরকার-ঘেঁষা ও নিরপেক্ষ পোর্টালে গুরুত্ব পেলেও সমালোচক পোর্টালগুলোতে প্রায় অনুপস্থিত।',
    reportCount: 7, portalCount: 6,
    updated: '৫ ঘণ্টা আগে', firstPublished: 'সকাল ৯:১০',
    blindspot: 'critic', blindspotNote: 'সমালোচক পোর্টালে একটিও নেই',
    reports: [
      { src: 'janakantha',   stance: 'govt',    time: '৯:১০',  headline: 'রপ্তানিতে ইতিহাস গড়ল বাংলাদেশ' },
      { src: 'kaler-kantho', stance: 'govt',    time: '৯:৪০',  headline: 'রেকর্ড রপ্তানি আয়ে অর্থনীতিতে সুবাতাস' },
      { src: 'bd-protidin',  stance: 'govt',    time: '১০:০৫', headline: 'সরকারের নীতির সাফল্যে রপ্তানিতে নতুন মাইলফলক' },
      { src: 'bdnews24',     stance: 'neutral', time: '১০:৪০', headline: 'রপ্তানি আয়ে প্রবৃদ্ধি, তবে এক খাতেই কেন্দ্রীভূত' },
      { src: 'prothom-alo',  stance: 'neutral', time: '১১:২০', headline: 'রেকর্ড রপ্তানি: সংখ্যার পেছনের হিসাব-নিকাশ' },
      { src: 'jugantor',     stance: 'govt',    time: '১১:৫০', headline: 'রপ্তানি প্রবৃদ্ধিতে উজ্জ্বল সম্ভাবনার হাতছানি' },
    ],
  },
  {
    id: 'power-cost', topic: 'অর্থনীতি',
    title: 'বিদ্যুৎ প্রকল্পে ব্যয় বৃদ্ধি নিয়ে সংসদীয় কমিটির প্রশ্ন',
    summary: 'একটি বৃহৎ বিদ্যুৎ প্রকল্পের ব্যয় তৃতীয় দফা বাড়ানোর প্রস্তাব নিয়ে প্রশ্ন তুলেছে সংসদীয় কমিটি। খবরটি নিরপেক্ষ ও সমালোচক পোর্টালে গুরুত্ব পেলেও সরকার-ঘেঁষা পোর্টালে প্রায় নেই।',
    reportCount: 6, portalCount: 5,
    updated: '৬ ঘণ্টা আগে', firstPublished: 'সকাল ৯:২৫',
    blindspot: 'govt', blindspotNote: 'ঘেঁষা পোর্টালে প্রায় নেই',
    reports: [
      { src: 'prothom-alo',  stance: 'neutral', time: '৯:২৫',  headline: 'বিদ্যুৎ প্রকল্পে তৃতীয় দফা ব্যয় বৃদ্ধির প্রস্তাব' },
      { src: 'bdnews24',     stance: 'neutral', time: '১০:১০', headline: 'প্রকল্প ব্যয় নিয়ে সংসদীয় কমিটির প্রশ্ন' },
      { src: 'manabzamin',   stance: 'critic',  time: '১১:০০', headline: 'ব্যয় বাড়ে, কাজ এগোয় না — কার পকেটে যাচ্ছে টাকা?' },
      { src: 'naya-diganta', stance: 'critic',  time: '১১:৪০', headline: 'মেগা প্রকল্পের নামে মেগা অপচয়ের অভিযোগ' },
      { src: 'samakal',      stance: 'critic',  time: '১২:২০', headline: 'জবাবদিহি ছাড়া ব্যয় বৃদ্ধি কতদিন?' },
    ],
  },
  {
    id: 'padma-toll', topic: 'পরিবহন',
    title: 'পদ্মা সেতুতে একদিনে টোল আদায়ে রেকর্ড',
    summary: 'ঈদযাত্রার চাপে পদ্মা সেতুতে একদিনে টোল আদায়ের নতুন রেকর্ড হয়েছে বলে জানিয়েছে সেতু কর্তৃপক্ষ। খবরটি সমালোচক পোর্টালগুলোতে প্রায় অনুপস্থিত।',
    reportCount: 6, portalCount: 5,
    updated: '৭ ঘণ্টা আগে', firstPublished: 'সকাল ৮:৪৫',
    blindspot: 'critic', blindspotNote: 'সমালোচক পোর্টালে প্রায় নেই',
    reports: [
      { src: 'kaler-kantho', stance: 'govt',    time: '৮:৪৫',  headline: 'পদ্মা সেতুতে টোল আদায়ে নতুন ইতিহাস' },
      { src: 'janakantha',   stance: 'govt',    time: '৯:২০',  headline: 'স্বপ্নের সেতুতে রেকর্ড আয়, গর্বিত দেশ' },
      { src: 'bd-protidin',  stance: 'govt',    time: '৯:৫৫',  headline: 'একদিনে সাড়ে চার কোটি টাকার টোল আদায়' },
      { src: 'bdnews24',     stance: 'neutral', time: '১০:৩০', headline: 'ঈদযাত্রায় পদ্মা সেতুতে রেকর্ড টোল আদায়' },
      { src: 'ittefaq',      stance: 'neutral', time: '১১:১০', headline: 'পদ্মা সেতুতে যান চলাচল ও টোল — দুটোই রেকর্ড' },
    ],
  },
];
